# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab6.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lab6.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\x12\x0brestcompare\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x88\x02\n\x0bRestCompare\x12\x31\n\x03\x61\x64\x64\x12\x13.restcompare.addMsg\x1a\x15.restcompare.addReply\x12\x46\n\ndotProduct\x12\x1a.restcompare.dotProductMsg\x1a\x1c.restcompare.dotProductReply\x12=\n\x08rawImage\x12\x18.restcompare.rawImageMsg\x1a\x17.restcompare.imageReply\x12?\n\tjsonImage\x12\x19.restcompare.jsonImageMsg\x1a\x17.restcompare.imageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMSG']._serialized_start=27
  _globals['_ADDMSG']._serialized_end=57
  _globals['_RAWIMAGEMSG']._serialized_start=59
  _globals['_RAWIMAGEMSG']._serialized_end=85
  _globals['_DOTPRODUCTMSG']._serialized_start=87
  _globals['_DOTPRODUCTMSG']._serialized_end=124
  _globals['_JSONIMAGEMSG']._serialized_start=126
  _globals['_JSONIMAGEMSG']._serialized_end=153
  _globals['_ADDREPLY']._serialized_start=155
  _globals['_ADDREPLY']._serialized_end=178
  _globals['_DOTPRODUCTREPLY']._serialized_start=180
  _globals['_DOTPRODUCTREPLY']._serialized_end=217
  _globals['_IMAGEREPLY']._serialized_start=219
  _globals['_IMAGEREPLY']._serialized_end=262
  _globals['_RESTCOMPARE']._serialized_start=265
  _globals['_RESTCOMPARE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
